Module8 task1
htmlacademy-javascript/1485695-kekstagram-23 pull request #6
Opened 2021-06-24 12:56 UTC by nadyavilboa

2021-06-24 14:43 UTC, Manyaka commented on js/utils.js
> +  const re = /^#[A-Za-zА-Яа-я0-9]{1,19}$/;
регэкпу так не сокращают - `regExp` - вот так пишут

2021-06-24 14:44 UTC, Manyaka commented on js/utils.js
> +  const re = /^#[A-Za-zА-Яа-я0-9]{1,19}$/;
название ф-и неудачное - валидация хештега на что?

2021-06-24 14:49 UTC, Manyaka commented on js/popup-editor.js
> +let validationHashtagsIsOk = false;
```suggestion
let isHashtagsValid = false;
```
молодец, что додумалась до `is`!

2021-06-24 14:55 UTC, Manyaka commented on js/popup-editor.js
> +import { isEnterEvent, isEscapeEvent, validateHashtag, checkLengthLine } from './utils.js';
слишком большой модуль, он у тебя и попап открывает / закрывает и еще и валидирует хештеги - разбей на два как минимум

2021-06-24 14:56 UTC, Manyaka commented on js/popup-editor.js
> +function checkInputHashtags () {
тут валидация - validate, ну и хештеги они полюбому в инпуте, поэтому эта информация избыточна, просто валидацияХештегов

2021-06-24 14:56 UTC, Manyaka commented on js/popup-editor.js
> +  }
отдели пустыми строками, будет поприятнее читать

2021-06-24 14:56 UTC, Manyaka commented on js/popup-editor.js
> +function sendForm (evt) {
во, тут у тебя еще и третье действие - отправка формы

2021-06-24 20:02 UTC, nadyavilboa commented on js/utils.js
> +  const re = /^#[A-Za-zА-Яа-я0-9]{1,19}$/;
не понимаю коммент. Вроде validate это глагол? Валидировать хэш-тег. проверить то есть на соответствие правилу. Я сейчас переименовала checkHastagMatchesRule - проверить хэш-тег соответствует правилу

2021-06-25 05:23 UTC, Manyaka requested changes

2021-06-25 05:23 UTC, Manyaka commented on js/popup-editor.js
> +function closePopupIfEventEscape (evt) {
неудачное название ф-и. Нельзя в ней писать условие, при которой она сработает, тк логика условия закладывается в том месте, где эта функция вызывается

2021-06-25 05:23 UTC, Manyaka commented on js/popup-editor.js
> +function closePopupIfEventEnter (evt) {
неудачное название аналогично коменту выше

2021-06-25 05:23 UTC, Manyaka commented on js/popup-editor.js
> +function openPopup () {
вот удачное название, 2 слова - глагол и существительное, глагол означает что эта функция делает, существительное - с чем/над чем.

2021-06-25 05:23 UTC, Manyaka commented on js/popup-editor.js
> +inputFilePicture.addEventListener('change', openPopup);
```suggestion
inputFilePicture.addEventListener('change', inputFilePictureChangeHanlder);
// выбери как хочешь именовать через on или через handler
inputFilePicture.addEventListener('change', onInputFilePictureChange);
```

https://up.htmlacademy.ru/javascript/23/criteries#d4

> Из названия обработчика события и функции-колбэка следует, что это обработчик.

2021-06-25 05:23 UTC, Manyaka commented on js/popup-editor.js
> +buttonCloseEditor.addEventListener('click', closePopup);
```suggestion
buttonCloseEditor.addEventListener('click', buttonCloseEditorClickHandler);
buttonCloseEditor.addEventListener('click', onButtonCloseEditorClick);
```

2021-06-25 05:23 UTC, Manyaka commented on js/popup-editor.js
> +  document.addEventListener('keydown', closePopupIfEventEscape);
```suggestion
  document.addEventListener('keydown', documentKeydownHandler);
  document.addEventListener('keydown', onDocumentKeydown);
```

2021-06-25 05:23 UTC, Manyaka commented on js/popup-editor.js
> +  document.addEventListener('keydown', closePopupIfEventEscape);
ну и тд поправь

2021-06-29 12:43 UTC, Manyaka requested changes

2021-06-29 12:43 UTC, Manyaka commented on js/input-validation.js
> +    allHushtagsCorrect: allHushtagsCorrect,
```suggestion
    allHashtagsCorrect: allHashtagsCorrect,
```

2021-06-29 12:43 UTC, Manyaka commented on js/input-validation.js
> +    noHastagMatches: noHastagMatches,
```suggestion
    noHashtagMatches: noHashtagMatches,
```

2021-06-29 12:43 UTC, Manyaka commented on js/input-validation.js
> +    noTooMuchHastags: noTooMuchHastags,
```suggestion
    noTooMuchHashtags: noTooMuchHashtags,
```

2021-06-29 12:43 UTC, Manyaka commented on js/input-validation.js
> +  const noTooMuchHastags = hashtags.length <= 5;
магическое число

2021-07-01 16:11 UTC, Manyaka requested changes

2021-07-01 16:11 UTC, Manyaka commented on js/input-validation.js
> +  const regExp = /^#[A-Za-zА-Яа-я0-9]{1,19}$/;
19 - магическое число

2021-07-02 06:24 UTC, merged